version: '3.8'
services:
  api:
    depends_on:
      - api-postgres
    image: orm_migrate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://db_user:db_password@localhost:5432/db_name
  api-postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amibamcx3700
      POSTGRES_DB: netology_orm_migrations
    restart: always
